
[package]
name = "finobinos/numberutil"
description = "NumberUtil"
version = "1.1.5"
license = "Apache-2.0"
authors = ["finobinos"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"