
[package]
name = "finobinos/signal"
description = "Signal class"
version = "1.2.2"
license = "Apache-2.0"
authors = ["finobinos"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"