
[package]
name = "finobinos/tableutil"
description = "TableUtil"
version = "1.1.6"
license = "Apache-2.0"
authors = ["finobinos"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"