
[package]
name = "finobinos/timer"
description = "Timer class"
version = "1.3.0"
license = "Apache-2.0"
authors = ["finobinos"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "finobinos/signal@1.2.2"