
[package]
name = "finobinos/binder"
description = "Binder class"
version = "1.1.4"
license = "Apache-2.0"
authors = ["finobinos"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "finobinos/signal@1.2.2"
Maid = "finobinos/maid@1.2.4"
Promise = "evaera/promise@3.1.0"
Remote = "finobinos/remote@1.3.6"
