
[package]
name = "finobinos/remote"
description = "RemoteUtil"
version = "1.3.6"
license = "Apache-2.0"
authors = ["finobinos"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Maid = "finobinos/maid@1.2.4"
Promise = "evaera/promise@3.1.0"
TableUtil = "finobinos/tableutil@1.1.6"
Signal = "finobinos/signal@1.2.2"